Set custom user agent
awslabs/amazon-qldb-shell pull request #212
Opened 2021-10-06 21:00 UTC by guyilin-amazon

*Issue #, if available:*
#196 
*Description of changes:*
Set customized user agent, now the user agent will be like `aws-sdk-rust/0.1.0 api/QLDB Driver for Rust v0.1.0/QLDB Shell for Rust v2.0.0 os/macos lang/rust/1.55.0`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-10-06 21:07 UTC, marcbowes requested changes

2021-10-06 21:07 UTC, marcbowes commented on src/awssdk_driver.rs
> +const SHELL_VERSION: &'static str = "QLDB Shell for Rust v2.0.0";
Please can you use the same mechanism as was previously in use, where we don't need to manually keep this up to date?

2021-10-06 21:09 UTC, marcbowes commented on src/awssdk_driver.rs
> +const SHELL_VERSION: &'static str = "QLDB Shell for Rust v2.0.0";
https://github.com/awslabs/amazon-qldb-shell/blob/b18304949f98f26b29428400275ddb86f0c68f5e/src/rusoto_driver.rs#L96-L101

2021-10-06 21:59 UTC, marcbowes commented
Also, since it's hard to write a test for this, can you show evidence that this works? For example, you can enable file logging in the config and then look at a sample request. Alternatively, you can look at a request on the service side and check the metrics work.

2021-10-12 19:12 UTC, marcbowes commented on Cargo.toml
>  amazon-qldb-driver = { git = "https://github.com/awslabs/amazon-qldb-driver-rust", package = "amazon-qldb-driver", branch = "main" }
We need to get the sdk updated in the driver too.

2021-10-12 19:30 UTC, merged

2021-11-18 15:15 UTC, rcoh commented
FYI: this can be tested quite easily by using `capture_request()`: https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/aws-smithy-client/src/test_connection.rs#L75-L106

(note: `test-util` must be enabled)